### ISSUE TITLE
Getting error while running ARemRecorder : couldn't find "libframebuffer.so"

### ISSUE THREAD

**Issue by gargsunil** [donaldmunro/AARemu#1]
Hi,

On compiling "ARemRecorder" getting the error: 
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/to.augmented.reality.android.em.recorder-1/base.apk"],nativeLibraryDirectories=[/data/app/to.augmented.reality.android.em.recorder-1/lib/arm, /data/app/to.augmented.reality.android.em.recorder-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find **"libframebuffer.so"**
                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at to.augmented.reality.android.em.recorder.NativeFrameBuffer.<clinit>(NativeFrameBuffer.java:36)
                      at to.augmented.reality.android.em.recorder.GLRecorderRenderer.openCamera(GLRecorderRenderer.java:395)
                      at to.augmented.reality.android.em.recorder.GLRecorderRenderer.startPreview(GLRecorderRenderer.java:597)
                      at to.augmented.reality.android.em.recorder.ARSurfaceView.startPreview(ARSurfaceView.java:149)
                      at to.augmented.reality.android.em.recorder.RecorderActivity$5$1.run(RecorderActivity.java:380)
                      at android.app.Activity.runOnUiThread(Activity.java:5573)
                      at to.augmented.reality.android.em.recorder.RecorderActivity$5.surfaceChanged(RecorderActivity.java:371)
                      at android.view.SurfaceView.updateWindow(SurfaceView.java:608)
                      at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:243)
                      at android.view.View.dispatchWindowVisibilityChanged(View.java:9653)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
                      at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1310)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1410)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                      at android.view.Choreographer.doFrame(Choreographer.java:608)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
                      at android.os.Handler.handleCallback(Handler.java:742)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:5523)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/MQSEventManagerDelegate: failed to get MQSService.

Can somebody please take a look and help me in fixing it.

Thanks!

**Comment by neokeld** [comment]
@gargsunil You should retry with the recently updated code source of AARemu
@donaldmunro Thanks a lot for your effort on this project and the new version which converts the C++ code to use CMake and updating it to the new Android Studio 4 version.
